sudo: required
services: 
  - docker

before_install: 
  - docker build -t yangdenny/docker-react -f Dockerfile.dev .

script:
  - docker run yangdenny/docker-react npm run test -- --coverage

deploy:
  provider: elasticbeanstalk
  region: "us-west-1"
  app: "DockerReact"
  env: "Dockerreact-env"
  bucket_name: "elasticbeanstalk-us-west-1-256365000393"
  bucket_path: "DockerReact"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key:
        secure: "$AWS_SECRET_KEY" 
 
